modLoader = "javafml"
loaderVersion = "[36,)"
license="Apache License 2.0"

[[mods]]
modId = "papi"
version = "${version}"
displayName = "Papi"
authors="Team Potato"
description = '''
Another Fabric API Reforged Project.

Essential hooks for modding with Fabric ported to MinecraftForge.
'''