modLoader = "javafml"
loaderVersion = "[36,)"
license="Apache License 2.0"

[[mods]]
modId = "papi"
logoFile = "icon.png"
version = "${version}"
displayName = "Papi"
authors="Team Potato"
description = '''
Another Fabric API Reforged Project
'''
